Perl update
Due to Perl update i couldnt compile this on Ubuntu 16.04
error: Can't use 'defined(@array)' (Maybe you should just omit the defined()?)
Perl explanation from(http://perldoc.perl.org/perldiag.html)
defined() is not useful on arrays because it checks for an undefined scalar value. If you want to see if the array is empty, just use if (@array) { # not empty } for example.
so i just removed defined and it compiles...